// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository/repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	reflect "reflect"

	models "github.com/arthurshafikov/boilerplate/internal/core/models"
	types "github.com/arthurshafikov/boilerplate/internal/core/types"
	gomock "github.com/golang/mock/gomock"
)

// MockBaseRepo is a mock of BaseRepo interface.
type MockBaseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBaseRepoMockRecorder
}

// MockBaseRepoMockRecorder is the mock recorder for MockBaseRepo.
type MockBaseRepoMockRecorder struct {
	mock *MockBaseRepo
}

// NewMockBaseRepo creates a new mock instance.
func NewMockBaseRepo(ctrl *gomock.Controller) *MockBaseRepo {
	mock := &MockBaseRepo{ctrl: ctrl}
	mock.recorder = &MockBaseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseRepo) EXPECT() *MockBaseRepoMockRecorder {
	return m.recorder
}

// WrapInTransaction mocks base method.
func (m *MockBaseRepo) WrapInTransaction(ctx *types.Context, txFunc types.TXFunction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WrapInTransaction", ctx, txFunc)
	ret0, _ := ret[0].(error)
	return ret0
}

// WrapInTransaction indicates an expected call of WrapInTransaction.
func (mr *MockBaseRepoMockRecorder) WrapInTransaction(ctx, txFunc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WrapInTransaction", reflect.TypeOf((*MockBaseRepo)(nil).WrapInTransaction), ctx, txFunc)
}

// MockTest is a mock of Test interface.
type MockTest struct {
	ctrl     *gomock.Controller
	recorder *MockTestMockRecorder
}

// MockTestMockRecorder is the mock recorder for MockTest.
type MockTestMockRecorder struct {
	mock *MockTest
}

// NewMockTest creates a new mock instance.
func NewMockTest(ctrl *gomock.Controller) *MockTest {
	mock := &MockTest{ctrl: ctrl}
	mock.recorder = &MockTestMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTest) EXPECT() *MockTestMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTest) Create(ctx context.Context, model models.TestModel) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, model)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTestMockRecorder) Create(ctx, model interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTest)(nil).Create), ctx, model)
}
