services:
    # app:
    #     build:
    #         context: ../.
    #         dockerfile: ./build/app/Dockerfile
    #         target: dev
    #     environment:
    #         WAIT_HOSTS: pgsql:5432
    #     depends_on: 
    #         - pgsql
    pgsql:
        image: postgres:16.3
        restart: unless-stopped
        ports:
            - "54403:5432"
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
    # adminer:
    #     image: adminer
    #     restart: unless-stopped
    #     ports:
    #         - "54404:8080"
    #     depends_on:
    #         - pgsql
