services:
    # app:
    #     build:
    #         context: ../.
    #         dockerfile: ./build/app/Dockerfile
    #         target: dev
    #     environment:
    #         WAIT_HOSTS: minio:9000
    #     depends_on: 
    #         - minio
